# Generated by Django 5.0.2 on 2024-02-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_previouse_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('TAKEN', 'Taken'), ('DONE', 'Done')], default='new', max_length=5, verbose_name='Состояние'),
        ),
    ]
